sonar.verbose=true
sonar.organization=sthiyam-devops-training-level1
sonar.projectKey=sthiyam-devops-training-level1_sthiyatrend
sonar.projectName=sthiyatrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
